### ISSUE TITLE
Singular Noun Names

### ISSUE THREAD

**Issue by chimalsky** [hotwired-laravel/turbo-laravel#10]
Hi, I was wondering if there was an easy 'configuration' based way to be able to use singular nouns rather than the conventional plural.

So instead of `comments.create` and `comments.store` package would look for `comment.create` and `comment.store`

Thank you, @tonysm so much for this package.

**Comment by tonysm** [comment]
Hey, there

Uhm, that sounds like something we could do. I'll experiment with that tonight.

**Comment by tonysm** [comment]
Just to be sure, you only need that at the routing layer? What about the view folder names (they also get plural version of the resource name)?

**Comment by chimalsky** [comment]
I was thinking for everything. I figured this was possible because I assume names are being resolved all within one class https://github.com/tonysm/turbo-laravel/blob/main/src/NamesResolver.php

If it's too hard to do any nobody else asks for this then no worries.

**Comment by tonysm** [comment]
Closing this. Not sure if worth customizing. If anyone thinks it's a nice addition, pls feel free to send a PR.

**Comment by tonysm** [comment]
Hey, @chimalsky, as I was working on adding support for a partial pattern of `{plural}.partials.{singular}` instead of the default `{plural}._{singular}`, I remembered this issue. I thought you were asking for the same thing. However, when I re-read, you asked for singular resource names in the route. That already works. We only depend on the suffix of the route name, `*.create` and `*.store`, `*.edit` and `*.update`, and so on.... It doesn't matter if the resource name is plural, singular, or whatever word is in there.

Anyways, sorry for such a late reply, I must have misread your issue back then.
