### ISSUE TITLE
Redirecting to an external link

### ISSUE THREAD

**Issue by bilogic** [hotwired-laravel/turbo-laravel#111]
When using normal blade and HTTP, we sometimes redirect to an external domain/link. Is there a way to do this with turbo stream?

I'm hoping to use the button tag and javascript, instead of styling an A tag to look like a button and disable turbo :)

**Comment by tonysm** [comment]
@bilogic not sure what you mean. If you want to redirect the user to an external site after a form submit, I think you can do that just normally. Turbo only turns that into a visit if it's for the same origin ([docs](https://turbo.hotwired.dev/handbook/drive#setting-a-root-location)), otherwise it will fallback to a full page visit.

Let me know if that's helpful to you.
